### ISSUE TITLE
Mutliple droplets within same namespace?

### ISSUE THREAD

**Issue by WCLLTD** [vprokopov-do/do-snap#1]
Hi Vasily, hope you are well!

I've been reviewing this and have been able to setup for a single droplet - however, when trying to setup for multiple Droplets within same namespace, it appears to error out:

------------------

sam@WCL-L-011:~/scripts/do-snap/packages(main)$ doctl serverless deploy do-snap
Deploying '/home/sam/scripts/do-snap/packages/do-snap'
  to namespace 'fn-04615d72-19ee-4fa6-b027-de86e928220d'
  on host 'https://faas-lon1-917a94a7.doserverless.co'

Nothing deployed

------------------

Is this supported by the script? Or will I need to create a new name space for each backup/droplet required? 

Thank you!

Sam

**Comment by WCLLTD** [comment]
Hi Vasily

Please ignore this, all resolved, by running the deploy command correctly!

For ref - you need to run the deploy command on the entire cloned down folder - or you can CD to repo and run:
doctl serverless deploy .


Thanks again!
Sam

**Comment by WCLLTD** [comment]
Hi @vprokopov-do 

Me again!

Getting a weird error, all my config seemingly looks to be correct and getting after successfuly setting up the script across 3 different droplets.

![image](https://github.com/vprokopov-do/do-snap/assets/120101700/0655ff63-7485-4096-b7c7-3203432d7346)

Request failed with status code 422
Cannot process the request because it is semantically incorrect.


Have you seen the above error before at all? I imagine this is due to me passing multiple of the same var and the call becoming ambiguios? Or something along these lines?

Any help would be appreciated!!


Thanks
Sam

**Comment by vprokopov-do** [comment]
Hey Sam, thank you for reporting this. Currently Triggers are in Beta and there's limit of 3 Triggers per Namespace. To work around this I've

**Comment by ghost** [comment]
Hey Sam, thanks for reporting this! Triggers are still in Beta, and they come with a limit of 3 per Namespace, which I didn't know. 

To get around this, I've tweaked the code. Now, instead of providing a single Droplet ID, you have the flexibility to enter a comma-separated list of Droplet IDs. All these Droplets will get snapped up at the same time following the same cron schedule. 

Hope this change suits your needs. It's the way to go if you want to handle more than three Droplets. Please give it a try and let me know if it works for you. Have an awesome weekend!

/ Vasily
